[package]
name = "pfru"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["derive"] }
inquire = "0.7.5"
lua-patterns = "0.4.0"
owo-colors = "4.2.0"
strfmt = "0.2.4"
